version: '2'
services:
    klov:
        image: anshooarora/klov:1.0.1
        container_name: klov
        environment:
            - SPRING_DATA_MONGODB_URI=mongodb://{host}:{port}
        ports:
            - 90:90
